name: hello-world

on:
  schedule:
    - cron: '10 * * * *'
  workflow_dispatch: 

  
jobs:
  hello-world-job:
    name: date-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Dotnet run
        run: |
            cd ./MireaScheduleUpdates/
            dotnet run
            echo date.txt
            git config user.name github-actions
            git config user.email github-actions@github.com
            git checkout feature-console-text-write
            git add .
            git commit -m "generated"
            git push

