name: hello-world

on:
  schedule:
    - cron: '10 * * * *'
  workflow_dispatch:
permissions: write-all

jobs:
  hello-world-job:
    name: date-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Dotnet run
        run: |
            cd ./MireaScheduleUpdates/
            dotnet run
