name: hello-world

on:
  schedule:
    - cron: '10 * * * *'
  workflow_dispatch:
permissions: write-all

concurrency:
  group: ${{ github.ref }}

jobs:
  send_schedule_updates:
    name: date-job
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4
      - name: Dotnet run
        env:
            InCI: 'true'
            ADMIN_PACHKA_SECRET: ${{ secrets.ADMIN_PACHKA_SECRET }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            cd ./MireaScheduleUpdates/
            dotnet run
